export const clientesEjemplo= [
  { id: 1, nombre: "Juan Pérez", contacto: "juan@email.com" },
  { id: 2, nombre: "María García", contacto: "maria@email.com" },
  { id: 3, nombre: "Carlos López", contacto: "carlos@email.com" },
  { id: 4, nombre: "Ana Martínez", contacto: "ana@email.com" },
  { id: 5, nombre: "Luis Rodríguez", contacto: "luis@email.com" },
]

export const muestrasEjemplo = [
  {
    id: 1,
    tipoPrenda: "Remera",
    pesoKilos: 0.25,
    estadoMuestra: "realizado",
    proceso: "batik",
    cliente: clientesEjemplo[0],
    fechaCreacion: new Date("2024-01-10"),
  },
  {
    id: 2,
    tipoPrenda: "Pantalón",
    pesoKilos: 0.35,
    estadoMuestra: "entregado",
    proceso: "nevado",
    cliente: clientesEjemplo[1],
    fechaCreacion: new Date("2024-01-15"),
  },
  {
    id: 3,
    tipoPrenda: "Vestido",
    pesoKilos: 0.3,
    estadoMuestra: "realizado",
    proceso: "degradé",
    cliente: clientesEjemplo[2],
    fechaCreacion: new Date("2024-01-20"),
  },
  {
    id: 4,
    tipoPrenda: "Camisa",
    pesoKilos: 0.28,
    estadoMuestra: "entregado",
    proceso: "quebrado",
    cliente: clientesEjemplo[3],
    fechaCreacion: new Date("2024-01-25"),
  },
  {
    id: 5,
    tipoPrenda: "Falda",
    pesoKilos: 0.22,
    estadoMuestra: "realizado",
    proceso: "gel",
    cliente: clientesEjemplo[4],
    fechaCreacion: new Date("2024-02-01"),
  },
  {
    id: 6,
    tipoPrenda: "Remera",
    pesoKilos: 0.26,
    estadoMuestra: "entregado",
    proceso: "otro",
    cliente: clientesEjemplo[0],
    fechaCreacion: new Date("2024-02-05"),
  },
]